//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClkCam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> EmendatorAdminId { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Tag { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Category Category { get; set; }
        public virtual Admin Admin1 { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
